### ISSUE TITLE
longs not read properly

### ISSUE THREAD

**Issue by klbostee** [klbostee/ctypedbytes#1]
It’s currently not caught by the unit tests, but after adding .reads() (in order to avoid falling back to the pure-Python typedbytes module) in tests/testio.py you get:

```
Failure in test testio (tests.testio.TestIO) 
Traceback (most recent call last):
  File "/usr/lib/python2.6/unittest.py", line 279, in run
    testMethod()
  File "/mir/klaas/gits/ctypedbytes/tests/testio.py", line 23, in testio
    self.assertEqual(objects[index], record)
  File "/usr/lib/python2.6/unittest.py", line 350, in failUnlessEqual
    (msg or '%r != %r' % (first, second))
AssertionError: 3000000000 != -1294967296L
```

Hence, longs are not read properly by the implementation in C.

**Comment by klbostee** [comment]
Fixed by ff11e158310f5d14a4e0c6df3dc9fc12d9575981
